// ignore_for_file: constant_identifier_names

import '../../models/app_models.dart';

class AppConstants {
  // App Info
  static const String appName = 'SANTEO Connect';
  static const String appTagline = 'Votre kiné en poche, votre santé en main.';
  static const String appVersion = '1.0.0';

  // OpenAI
  static const String openAIBaseUrl = 'https://api.openai.com/v1/chat/completions';
  static const String openAIModel = 'gpt-4';

  // Disclaimer
  static const String disclaimer =
      'SANTEO Connect propose une approche de bien-être et de prévention complémentaire à votre parcours de santé. '
      'Cette plateforme ne remplace pas l\'avis d\'un professionnel de santé. '
      'En cas de douleur persistante ou aiguë, consultez un professionnel de santé.';

  // Territories
  static const List<String> territories = [
    'Nouvelle-Calédonie',
    'Polynésie française',
    'Wallis-et-Futuna',
    'Vanuatu',
    'Fidji',
    'Samoa',
    'Tonga',
    'Îles Cook',
    'Kiribati',
    'Autre territoire insulaire',
  ];

  // Health Goals
  static const List<String> healthGoals = [
    'Bouger sans gêne au quotidien',
    'Améliorer ma souplesse',
    'Renforcer mes muscles',
    'Retrouver la forme',
    'Prévention et bien-être',
    'Reprendre une activité physique',
    'Me sentir mieux dans mon corps',
  ];

  // Age Groups
  static const List<String> ageGroups = [
    '18-25 ans',
    '26-35 ans',
    '36-45 ans',
    '46-55 ans',
    '56-65 ans',
    '65+ ans',
  ];

  // Activity Levels
  static const List<String> activityLevels = [
    'Sédentaire (peu ou pas d\'exercice)',
    'Légèrement actif (1-2 jours/sem)',
    'Modérément actif (3-4 jours/sem)',
    'Très actif (5-6 jours/sem)',
    'Extrêmement actif (tous les jours)',
  ];

  // Pain Zones
  static const List<String> painZones = [
    'Cou / Nuque',
    'Épaules',
    'Bras / Coudes',
    'Mains / Poignets',
    'Haut du dos',
    'Bas du dos',
    'Hanches',
    'Genoux',
    'Chevilles / Pieds',
    'Abdominaux',
  ];

  // Health Problems
  static const List<String> healthProblems = [
    'Gêne au niveau du dos',
    'Raideurs articulaires',
    'Inconfort cervical',
    'Gêne aux épaules',
    'Manque d\'énergie',
    'Sédentarité prolongée',
    'Stress / Tensions',
    'Reprise d\'activité',
    'Aucune gêne particulière',
  ];

  // Exercise Preferences
  static const List<String> exercisePreferences = [
    'Étirements / Flexibilité',
    'Renforcement musculaire',
    'Mobilité articulaire',
    'Cardio léger',
    'Relaxation / Respiration',
    'Équilibre / Proprioception',
  ];

  // Session Durations
  static const List<String> sessionDurations = [
    '10 minutes',
    '20 minutes',
    '30 minutes',
  ];

  // Weekly Frequencies
  static const List<String> weeklyFrequencies = [
    '3 jours/semaine',
    '4 jours/semaine',
    '5 jours/semaine',
    '6 jours/semaine',
    '7 jours/semaine',
  ];

  // Difficulty Levels
  static const Map<String, String> difficultyLabels = {
    'facile': 'Facile',
    'moyen': 'Moyen',
    'difficile': 'Difficile',
  };

  // Exercise Types
  static const Map<String, String> exerciseTypeLabels = {
    'etirement': 'Étirement',
    'renforcement': 'Renforcement',
    'mobilite': 'Mobilité',
    'cardio': 'Cardio',
  };

  // ====== 33 EXERCICES RÉELS — URLs Google Drive ======
  static final List<Exercise> seedExercises = [
    Exercise(
      id: 'ex_abdos_2_temps',
      name: 'Abdos 2 temps',
      description: 'Renforcement abdominal progressif en 2 phases',
      duration: 3,
      difficulty: 'moyen',
      targetZone: 'abdominaux',
      type: 'renforcement',
      videoUrl: 'https://drive.google.com/file/d/1DWlHbxgLUsuQ6EX4BcLFQTUV0OXv3C5h/preview',
      series: 3,
      reps: 10,
      dureeSerieSec: 0,
      reposSec: 30,
      typeComptage: 'reps',
      voixIntro: 'On commence les abdos 2 temps. Allongez-vous sur le dos, genoux fléchis, pieds au sol. Mains derrière la tête, coudes bien ouverts.',
      voixPendant: 'Premier temps, soulevez les épaules en expirant. Deuxième temps, redescendez en inspirant. Contrôlé, sans tirer sur le cou.',
      voixFin: 'Excellent travail ! Vos abdominaux se renforcent à chaque répétition. Bien joué !',
    ),
    Exercise(
      id: 'ex_abdos_4_temps',
      name: 'Abdos 4 temps',
      description: 'Gainage abdominal profond en 4 phases de mouvement',
      duration: 3,
      difficulty: 'difficile',
      targetZone: 'abdominaux',
      type: 'renforcement',
      videoUrl: 'https://drive.google.com/file/d/14eoGWUe65E3mnte5hfZuq2Crt7uqHlwW/preview',
      series: 3,
      reps: 8,
      dureeSerieSec: 0,
      reposSec: 40,
      typeComptage: 'reps',
      voixIntro: 'Les abdos 4 temps, version avancée. Allongé sur le dos, genoux fléchis. Le bas du dos reste plaqué au sol pendant tout l\'exercice.',
      voixPendant: 'Temps 1, inspirez. Temps 2, contractez et soulevez. Temps 3, tenez. Temps 4, redescendez en expirant. Quatre temps, un mouvement.',
      voixFin: 'Bravo ! C\'est un exercice exigeant et vous l\'avez réussi. Votre sangle abdominale vous remercie !',
    ),
    Exercise(
      id: 'ex_auto_embrassade',
      name: 'Auto-embrassade',
      description: 'Étirement doux des épaules et du haut du dos',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'epaules',
      type: 'mobilite',
      videoUrl: 'https://drive.google.com/file/d/1LND1nBrmLNtenu0y4NXiBtshtS2DD2s7/preview',
      series: 3,
      reps: 0,
      dureeSerieSec: 30,
      reposSec: 15,
      typeComptage: 'chrono',
      voixIntro: 'L\'auto-embrassade. Debout ou assis, le dos droit. Croisez les bras devant vous comme pour vous enlacer, chaque main sur l\'épaule opposée.',
      voixPendant: 'Inspirez doucement. En expirant, serrez légèrement vers l\'avant. Sentez l\'étirement entre les omoplates. Respirez profondément.',
      voixFin: 'C\'est un geste de douceur envers vous-même. Vos épaules et votre dos vont mieux. Continuez comme ça !',
    ),
    Exercise(
      id: 'ex_baby_stretch',
      name: 'Baby Stretch',
      description: 'Posture de repos qui étire le bas du dos et les hanches',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'bas_dos',
      type: 'etirement',
      videoUrl: 'https://drive.google.com/file/d/1V1b_9xajKTeO-nweYtuokMSImOmvP5wZ/preview',
      series: 3,
      reps: 0,
      dureeSerieSec: 45,
      reposSec: 15,
      typeComptage: 'chrono',
      voixIntro: 'Le Baby Stretch, posture de repos et de récupération. Mettez-vous à genoux, puis asseyez-vous doucement sur vos talons.',
      voixPendant: 'Penchez-vous vers l\'avant, bras tendus ou le long du corps. Relâchez complètement. À chaque expiration, laissez le dos s\'allonger davantage.',
      voixFin: 'Magnifique. C\'est une posture de récupération profonde. Votre dos et vos hanches vous remercient.',
    ),
    Exercise(
      id: 'ex_bird_dog',
      name: 'Bird Dog',
      description: 'Renforcement du dos et gainage en équilibre quadrupède',
      duration: 3,
      difficulty: 'moyen',
      targetZone: 'dos',
      type: 'renforcement',
      videoUrl: 'https://drive.google.com/file/d/1K565Sz8GZMXk1eFpsAucxWzcMOshnvsk/preview',
      series: 3,
      reps: 10,
      dureeSerieSec: 0,
      reposSec: 30,
      typeComptage: 'reps',
      voixIntro: 'Le Bird Dog. À quatre pattes, mains sous les épaules, genoux sous les hanches. Le dos est horizontal, regard vers le sol.',
      voixPendant: 'En expirant, tendez le bras droit et la jambe gauche simultanément. Tenez 2 secondes. Revenez. Le bassin ne bouge pas.',
      voixFin: 'Excellent contrôle ! Cet exercice stabilise votre colonne et renforce tout votre dos en profondeur.',
    ),
    Exercise(
      id: 'ex_brasse_bras',
      name: 'Brasse Bras',
      description: 'Mobilisation des épaules en mouvement de brasse',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'epaules',
      type: 'mobilite',
      videoUrl: 'https://drive.google.com/file/d/1i10fxWUPeE7GGHwH9KB57OejOMtnO45B/preview',
      series: 2,
      reps: 10,
      dureeSerieSec: 0,
      reposSec: 20,
      typeComptage: 'reps',
      voixIntro: 'La brasse bras. Debout ou assis, dos droit. Tendez les deux bras devant vous, parallèles au sol.',
      voixPendant: 'Ouvrez les bras vers l\'extérieur, comme en nageant la brasse. Les omoplates se rapprochent. Revenez lentement. Ample et fluide.',
      voixFin: 'Vos épaules sont débloquées et mobilisées. C\'est exactement ce dont elles avaient besoin. Bravo !',
    ),
    Exercise(
      id: 'ex_cat_cow',
      name: 'Cat-Cow',
      description: 'Mobilisation vertébrale en alternance dos rond / dos creux',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'colonne',
      type: 'mobilite',
      videoUrl: 'https://drive.google.com/file/d/1vc3WxcujGgQmGunhwbRkvUuVBAQlbphI/preview',
      series: 1,
      reps: 10,
      dureeSerieSec: 0,
      reposSec: 0,
      typeComptage: 'reps',
      voixIntro: 'Le Cat-Cow, ou chat-vache. À quatre pattes, mains sous les épaules, genoux sous les hanches.',
      voixPendant: 'Inspirez en creusant le dos, tête qui se relève — c\'est la vache. Expirez en arrondissant, menton vers la poitrine — c\'est le chat. Lent et synchronisé.',
      voixFin: 'Parfait réveil de la colonne ! Cet exercice est votre meilleur ami chaque matin. Votre dos vous remercie.',
    ),
    Exercise(
      id: 'ex_child_pose_cobra',
      name: 'Child Pose & Cobra',
      description: 'Enchaînement posture enfant et cobra pour le dos',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'bas_dos',
      type: 'etirement',
      videoUrl: 'https://drive.google.com/file/d/1vvA-seSFRbmrtvnDfmIQcfC3AwZXtrHx/preview',
      series: 3,
      reps: 0,
      dureeSerieSec: 40,
      reposSec: 15,
      typeComptage: 'chrono',
      voixIntro: 'Posture enfant et cobra. Commencez à genoux, front au sol, bras tendus devant vous. Respirez profondément.',
      voixPendant: 'Glissez vers l\'avant pour le cobra, mains sous les épaules, poussez le buste vers le haut. Bassin au sol. Maintenez. Puis revenez en posture enfant.',
      voixFin: 'Superbe ! Cet enchaînement équilibre parfaitement votre colonne entre flexion et extension.',
    ),
    Exercise(
      id: 'ex_crossed_legs_forward_fold',
      name: 'Crossed Legs Forward Fold',
      description: 'Flexion avant assis en tailleur pour hanches et bas du dos',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'hanches',
      type: 'etirement',
      videoUrl: 'https://drive.google.com/file/d/1ddKPdN4rSn0Eq2g7ojItGuxLD_YAoNgS/preview',
      series: 3,
      reps: 0,
      dureeSerieSec: 40,
      reposSec: 15,
      typeComptage: 'chrono',
      voixIntro: 'Flexion avant en tailleur. Asseyez-vous confortablement en tailleur sur le sol. Grandissez-vous avant de commencer.',
      voixPendant: 'Posez les mains devant vous et glissez-les doucement vers l\'avant. Laissez la gravité faire le travail. Respirez profondément dans cet étirement.',
      voixFin: 'Excellent ! Vos hanches et votre bas du dos ont bien travaillé. Vous gagnez en souplesse progressivement.',
    ),
    Exercise(
      id: 'ex_dead_bug',
      name: 'Dead Bug',
      description: 'Gainage profond allongé avec membres opposés',
      duration: 3,
      difficulty: 'moyen',
      targetZone: 'abdominaux',
      type: 'renforcement',
      videoUrl: 'https://drive.google.com/file/d/1oTWAYyvtGJcddW9F_k9gHX3JQtAEudMK/preview',
      series: 3,
      reps: 10,
      dureeSerieSec: 0,
      reposSec: 30,
      typeComptage: 'reps',
      voixIntro: 'Le Dead Bug. Allongé sur le dos, bras tendus vers le plafond, genoux à 90 degrés. Le bas du dos est plaqué au sol — c\'est fondamental.',
      voixPendant: 'En expirant, descendez le bras droit et la jambe gauche sans toucher le sol. Revenez. Le dos ne décolle jamais. Contrôle total.',
      voixFin: 'Remarquable contrôle ! Votre gainage profond se renforce. C\'est le fondement d\'un dos solide.',
    ),
    Exercise(
      id: 'ex_down_dog',
      name: 'Down Dog',
      description: 'Triangle renversé, étirement de toute la chaîne postérieure',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'dos',
      type: 'etirement',
      videoUrl: 'https://drive.google.com/file/d/1l5n2og15lsIH1KAwgML244IcbUITSvwK/preview',
      series: 3,
      reps: 0,
      dureeSerieSec: 35,
      reposSec: 15,
      typeComptage: 'chrono',
      voixIntro: 'Down Dog, le chien tête en bas. À quatre pattes, poussez les hanches vers le haut et l\'arrière. Votre corps forme un triangle.',
      voixPendant: 'Talons vers le sol, tête entre les bras. Alternez les genoux pour mieux étirer les mollets. Respirez amplement.',
      voixFin: 'Toute votre chaîne postérieure a été étirée. Dos, mollets, ischio-jambiers — tout est libéré. Parfait !',
    ),
    Exercise(
      id: 'ex_elevateur_scapula',
      name: 'Élévateur de la scapula',
      description: 'Étirement de la nuque et de l\'élévateur de la scapula',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'nuque',
      type: 'mobilite',
      videoUrl: 'https://drive.google.com/file/d/1fM7k6cbGfTUOwCrA_f54CxON9irsaAiG/preview',
      series: 2,
      reps: 0,
      dureeSerieSec: 20,
      reposSec: 10,
      typeComptage: 'chrono_par_cote',
      voixIntro: 'Étirement de l\'élévateur de la scapula. Assis ou debout, dos droit. Tournez la tête légèrement vers la droite, puis inclinez-la vers l\'épaule droite.',
      voixPendant: 'Laissez le bras gauche pendre naturellement. Sentez l\'étirement le long du côté gauche du cou. Respirez doucement. Maintenez sans forcer.',
      voixFin: 'Vos tensions cervicales se relâchent. Cet exercice est précieux après une journée devant un écran.',
    ),
    Exercise(
      id: 'ex_extension_hanche_ventre',
      name: 'Extension hanche plat ventre',
      description: 'Renforcement fessiers et postérieurs en position ventrale',
      duration: 3,
      difficulty: 'moyen',
      targetZone: 'fessiers',
      type: 'renforcement',
      videoUrl: 'https://drive.google.com/file/d/1MbI6W66lT5wKDEHIH-ruIgUj3XTMJmcr/preview',
      series: 3,
      reps: 12,
      dureeSerieSec: 0,
      reposSec: 30,
      typeComptage: 'reps_par_cote',
      voixIntro: 'Extension de hanche plat ventre. Allongez-vous sur le ventre, bras le long du corps. Contractez les abdominaux pour protéger le bas du dos.',
      voixPendant: 'Levez lentement la jambe droite tendue, quelques centimètres du sol. Tenez 2 secondes. Redescendez doucement. Douze répétitions puis on change.',
      voixFin: 'Vos fessiers et muscles postérieurs sont renforcés. Ces muscles soutiennent tout votre bassin. Excellent !',
    ),
    Exercise(
      id: 'ex_extension_lombaire',
      name: 'Extension lombaire',
      description: 'Renforcement des muscles paravertébraux lombaires',
      duration: 3,
      difficulty: 'moyen',
      targetZone: 'bas_dos',
      type: 'renforcement',
      videoUrl: 'https://drive.google.com/file/d/1rFmle-QgK6ZeeHG0yHF96EeSE3W5DFtr/preview',
      series: 3,
      reps: 10,
      dureeSerieSec: 0,
      reposSec: 30,
      typeComptage: 'reps',
      voixIntro: 'Extension lombaire. Allongé sur le ventre, mains derrière la tête ou le long du corps. Contractez doucement les fessiers.',
      voixPendant: 'Soulevez légèrement le buste du sol en expirant. Ne tirez pas sur le cou. Tenez 2 secondes. Redescendez en inspirant. Mouvement contrôlé.',
      voixFin: 'Votre bas du dos est plus fort. Ces exercices protègent votre colonne au quotidien. Continuez !',
    ),
    Exercise(
      id: 'ex_flechisseurs_doigts_poignet',
      name: 'Fléchisseurs des doigts et du poignet',
      description: 'Mobilisation et étirement des poignets et avant-bras',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'poignets',
      type: 'mobilite',
      videoUrl: 'https://drive.google.com/file/d/1OssQ_z44OIcrmRgW9_5DVUpOoBs_Edx3/preview',
      series: 2,
      reps: 0,
      dureeSerieSec: 20,
      reposSec: 10,
      typeComptage: 'chrono_par_cote',
      voixIntro: 'Étirement des fléchisseurs. Tendez le bras droit devant vous, paume vers le haut. Avec l\'autre main, tirez doucement les doigts vers le bas.',
      voixPendant: 'Sentez l\'étirement dans l\'avant-bras. Maintenez sans forcer. Respirez normalement. Puis doigts vers le haut pour l\'autre sens.',
      voixFin: 'Vos poignets et avant-bras sont soulagés. Pensez à faire cet exercice régulièrement si vous travaillez sur écran.',
    ),
    Exercise(
      id: 'ex_fort_double_stretch',
      name: 'Fort Double Stretch',
      description: 'Double étirement profond de la chaîne postérieure',
      duration: 3,
      difficulty: 'moyen',
      targetZone: 'ischio_jambiers',
      type: 'etirement',
      videoUrl: 'https://drive.google.com/file/d/1YXk9aZdYuGnt6r-DvOACl2JbV-2oqzlc/preview',
      series: 3,
      reps: 0,
      dureeSerieSec: 35,
      reposSec: 15,
      typeComptage: 'chrono',
      voixIntro: 'Fort Double Stretch. Debout, jambes écartées. Penchez-vous vers l\'avant, mains vers le sol. Repoussez les hanches vers l\'arrière.',
      voixPendant: 'Le dos reste long, les genoux légèrement fléchis. Alternez le poids d\'un côté puis de l\'autre pour intensifier l\'étirement. Respirez profondément.',
      voixFin: 'Toute votre chaîne postérieure a été travaillée en profondeur. Vous sentez la différence ? Excellent travail !',
    ),
    Exercise(
      id: 'ex_gainage_crunch',
      name: 'Gainage Crunch',
      description: 'Renforcement abdominal dynamique en position de planche',
      duration: 3,
      difficulty: 'moyen',
      targetZone: 'abdominaux',
      type: 'renforcement',
      videoUrl: 'https://drive.google.com/file/d/1k7u2YfK7XYLj8dL3KanIWQJxE3HPbffM/preview',
      series: 3,
      reps: 12,
      dureeSerieSec: 0,
      reposSec: 30,
      typeComptage: 'reps_par_cote',
      voixIntro: 'Gainage crunch. Position de planche sur les avant-bras, corps bien aligné. Les épaules sont stables, le bassin neutre.',
      voixPendant: 'En expirant, ramenez le genou droit vers la poitrine, tenez une seconde, revenez. Alternez. Le bassin ne monte pas. Précis et contrôlé.',
      voixFin: 'Excellent ! Votre sangle abdominale et votre stabilité de hanche progressent ensemble. C\'est une belle combinaison !',
    ),
    Exercise(
      id: 'ex_gainage_lateral_jambes',
      name: 'Gainage Latéral Jambes',
      description: 'Gainage latéral complet avec élévation de jambe',
      duration: 3,
      difficulty: 'difficile',
      targetZone: 'abdominaux_lateraux',
      type: 'renforcement',
      videoUrl: 'https://drive.google.com/file/d/1KClpsJcKgcvLpJSq-wFFzM1VTPmEzudG/preview',
      series: 3,
      reps: 10,
      dureeSerieSec: 0,
      reposSec: 35,
      typeComptage: 'reps_par_cote',
      voixIntro: 'Gainage latéral jambes. Sur le côté, appui sur le pied et l\'avant-bras. Corps en ligne droite. Hanche soulevée.',
      voixPendant: 'Levez doucement la jambe supérieure à 30 centimètres. Tenez 2 secondes. Redescendez avec contrôle. Le bassin ne bouge pas. Dix répétitions.',
      voixFin: 'Puissant ! Vos muscles latéraux sont fortement sollicités. Cela stabilise tout votre bassin et votre colonne.',
    ),
    Exercise(
      id: 'ex_gainage_lateral_genoux',
      name: 'Gainage Latéral Genoux',
      description: 'Version accessible du gainage latéral avec appui genoux',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'abdominaux_lateraux',
      type: 'renforcement',
      videoUrl: 'https://drive.google.com/file/d/1hlnEUpVQGFRZ54y8tbQUPvK52QdUTJDn/preview',
      series: 3,
      reps: 0,
      dureeSerieSec: 25,
      reposSec: 20,
      typeComptage: 'chrono_par_cote',
      voixIntro: 'Gainage latéral sur les genoux. Sur le côté, appui sur le genou et l\'avant-bras. Alignez hanches et épaules.',
      voixPendant: 'Soulevez le bassin pour former une ligne droite. Contractez les abdominaux. Respirez normalement. Tenez la position stable.',
      voixFin: 'Très bien ! Vous construisez votre gainage latéral progressivement. Continuez et la progression sera rapide !',
    ),
    Exercise(
      id: 'ex_hip_hinge',
      name: 'Hip Hinge',
      description: 'Apprentissage du pivot de hanche — mouvement fondamental',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'hanches',
      type: 'mobilite',
      videoUrl: 'https://drive.google.com/file/d/1l4rKRaQk0csBj0h6_Y9t3SV3PsoL1jgj/preview',
      series: 2,
      reps: 10,
      dureeSerieSec: 0,
      reposSec: 20,
      typeComptage: 'reps',
      voixIntro: 'Le Hip Hinge, le pivot de hanche. Debout, pieds écartés largeur de hanches. Mains sur les cuisses. C\'est un mouvement fondamental.',
      voixPendant: 'Poussez les fesses vers l\'arrière comme pour fermer une porte avec elles. Dos droit, genoux légèrement fléchis. Revenez. Charnière à la hanche.',
      voixFin: 'Le Hip Hinge est la base de tout. Vous venez d\'apprendre à protéger votre dos dans les gestes du quotidien. Excellent !',
    ),
    Exercise(
      id: 'ex_mountain_climber',
      name: 'Mountain Climber',
      description: 'Cardio intense en position de planche dynamique',
      duration: 3,
      difficulty: 'moyen',
      targetZone: 'abdominaux',
      type: 'cardio',
      videoUrl: 'https://drive.google.com/file/d/121mke-mXHhDion17SMvTWebxSihDIERY/preview',
      series: 3,
      reps: 20,
      dureeSerieSec: 0,
      reposSec: 40,
      typeComptage: 'reps',
      voixIntro: 'Mountain Climber. Planche haute, bras tendus, corps aligné. Cet exercice combine gainage et cardio. Adaptez le rythme à votre niveau.',
      voixPendant: 'Ramenez le genou droit vers la poitrine, revenez, puis le gauche. Hanches basses. Respirez régulièrement. Vingt répétitions alternées.',
      voixFin: 'Impressionnant ! Le Mountain Climber est l\'un des exercices les plus complets. Cardio, gainage, tout y est !',
    ),
    Exercise(
      id: 'ex_paravertebraux',
      name: 'Paravertébraux',
      description: 'Renforcement doux des muscles profonds du dos',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'dos',
      type: 'renforcement',
      videoUrl: 'https://drive.google.com/file/d/13hsokDk5dq8H5p3omsvSyanyG5YREdAC/preview',
      series: 3,
      reps: 10,
      dureeSerieSec: 0,
      reposSec: 25,
      typeComptage: 'reps_par_cote',
      voixIntro: 'Renforcement des paravertébraux. À quatre pattes, dos horizontal. Mouvement lent et précis.',
      voixPendant: 'Tendez le bras droit devant vous, parallèle au sol. Maintenez 3 secondes. Revenez. Puis le bras gauche. Pour progresser, ajoutez la jambe opposée.',
      voixFin: 'Votre dos se stabilise en profondeur. Les paravertébraux sont les muscles les plus importants pour prévenir les douleurs lombaires.',
    ),
    Exercise(
      id: 'ex_perfect_stretch',
      name: 'Perfect Stretch',
      description: 'Enchaînement d\'étirements globaux en position de fente',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'hanches',
      type: 'etirement',
      videoUrl: 'https://drive.google.com/file/d/1K9Jm_9MY6sPmWH8UrnquO2M_KO4rPQlc/preview',
      series: 2,
      reps: 0,
      dureeSerieSec: 35,
      reposSec: 15,
      typeComptage: 'chrono_par_cote',
      voixIntro: 'Le Perfect Stretch. Fente basse, genou droit au sol. Cet enchaînement libère tout le corps. Prenez votre temps.',
      voixPendant: 'Tournez doucement le buste vers la droite, ouvrez les bras. Puis posez la main droite au sol, levez le bras gauche vers le ciel. Respirez.',
      voixFin: 'Le Perfect Stretch porte bien son nom. Tout votre corps a été libéré. Vous pouvez sentir la différence !',
    ),
    Exercise(
      id: 'ex_planche_haute',
      name: 'Planche Haute',
      description: 'Gainage complet en appui sur les bras tendus',
      duration: 3,
      difficulty: 'moyen',
      targetZone: 'abdominaux',
      type: 'renforcement',
      videoUrl: null,
      series: 3,
      reps: 0,
      dureeSerieSec: 30,
      reposSec: 30,
      typeComptage: 'chrono',
      voixIntro: 'Planche haute. Mains au sol sous les épaules, bras tendus. Corps en ligne droite des talons à la tête. Contractez tout.',
      voixPendant: 'Abdominaux serrés, fessiers contractés, cuisses solides. Ne laissez pas les hanches monter ni descendre. Respirez régulièrement.',
      voixFin: 'La planche haute est l\'exercice roi du gainage. Vous renforcez l\'ensemble de votre corps. Bravo !',
    ),
    Exercise(
      id: 'ex_scorpion_stretch',
      name: 'Scorpion Stretch',
      description: 'Rotation vertébrale profonde en position ventrale',
      duration: 3,
      difficulty: 'moyen',
      targetZone: 'colonne',
      type: 'mobilite',
      videoUrl: null,
      series: 2,
      reps: 0,
      dureeSerieSec: 25,
      reposSec: 15,
      typeComptage: 'chrono_par_cote',
      voixIntro: 'Scorpion Stretch. Allongé sur le ventre, bras en croix, paumes vers le sol. Corps bien détendu.',
      voixPendant: 'Levez la jambe droite et croisez-la vers la gauche, pied vers le sol. Le regard suit dans la direction opposée. Sentez la rotation. Respirez dans cet espace.',
      voixFin: 'Votre colonne vertébrale a retrouvé de la mobilité en rotation. C\'est une sensation précieuse. Excellent travail !',
    ),
    Exercise(
      id: 'ex_seated_cat_cow',
      name: 'Seated Cat-Cow',
      description: 'Cat-Cow assis sur une chaise — idéal au bureau',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'colonne',
      type: 'mobilite',
      videoUrl: null,
      series: 1,
      reps: 10,
      dureeSerieSec: 0,
      reposSec: 0,
      typeComptage: 'reps',
      voixIntro: 'Seated Cat-Cow, le chat-vache assis. Sur votre chaise, deux pieds au sol, mains sur les genoux. Parfait pour le bureau.',
      voixPendant: 'Inspirez en creusant le dos, poitrine ouverte, tête légèrement levée. Expirez en arrondissant, menton vers la poitrine. Lent, synchronisé.',
      voixFin: 'C\'est tout ! En deux minutes, vous avez mobilisé toute votre colonne sans quitter votre chaise. Pensez-y plusieurs fois par jour !',
    ),
    Exercise(
      id: 'ex_seated_forward_fold',
      name: 'Seated Forward Fold',
      description: 'Flexion avant assis pour le dos et les jambes',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'dos',
      type: 'etirement',
      videoUrl: null,
      series: 3,
      reps: 0,
      dureeSerieSec: 40,
      reposSec: 15,
      typeComptage: 'chrono',
      voixIntro: 'Flexion avant assis. Jambes tendues devant vous. Inspirez en grandissant la colonne.',
      voixPendant: 'Expirez en vous penchant doucement vers l\'avant, mains vers les pieds. Pas de forçage. Laissez le dos s\'allonger. Chaque expiration vous rapproche un peu.',
      voixFin: 'Votre chaîne postérieure s\'est bien étirée. La souplesse se gagne avec la régularité. Vous êtes sur la bonne voie !',
    ),
    Exercise(
      id: 'ex_seated_forward_fold_split',
      name: 'Seated Forward Fold Split',
      description: 'Flexion avant avec jambes écartées en V',
      duration: 3,
      difficulty: 'moyen',
      targetZone: 'adducteurs',
      type: 'etirement',
      videoUrl: null,
      series: 3,
      reps: 0,
      dureeSerieSec: 35,
      reposSec: 15,
      typeComptage: 'chrono',
      voixIntro: 'Flexion avant jambes écartées. Assis, ouvrez les jambes en V large. Dos bien droit avant de vous pencher.',
      voixPendant: 'Penchez-vous vers le centre, puis vers la jambe droite, puis vers la gauche. Mains tendues dans chaque direction. Maintenez 30 secondes par position.',
      voixFin: 'Vos adducteurs et ischio-jambiers ont été bien étirés. Avec régularité, votre souplesse va s\'améliorer visiblement !',
    ),
    Exercise(
      id: 'ex_seated_pigeon_stretch',
      name: 'Seated Pigeon Stretch',
      description: 'Étirement profond de la hanche en position assise',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'hanches',
      type: 'etirement',
      videoUrl: null,
      series: 2,
      reps: 0,
      dureeSerieSec: 40,
      reposSec: 10,
      typeComptage: 'chrono_par_cote',
      voixIntro: 'Pigeon assis. Sur votre chaise, posez la cheville droite sur le genou gauche. Gardez le pied fléchi pour protéger le genou.',
      voixPendant: 'Penchez-vous doucement vers l\'avant. Sentez l\'étirement profond dans la fesse et la hanche. Respirez dans cet espace. Maintenez sans forcer.',
      voixFin: 'Vos hanches sont libérées. Le pigeon assis est remarquable pour soulager les tensions du bas du dos et des sciatiques.',
    ),
    Exercise(
      id: 'ex_split_unilateral',
      name: 'Split Unilatéral',
      description: 'Étirement unilatéral progressif des ischio-jambiers',
      duration: 3,
      difficulty: 'moyen',
      targetZone: 'ischio_jambiers',
      type: 'etirement',
      videoUrl: null,
      series: 2,
      reps: 0,
      dureeSerieSec: 35,
      reposSec: 15,
      typeComptage: 'chrono_par_cote',
      voixIntro: 'Split unilatéral. Assis au sol, une jambe tendue, l\'autre repliée sur le côté. Dos bien allongé avant de commencer.',
      voixPendant: 'Penchez-vous vers la jambe tendue, mains vers le pied. Dos long, pas arrondi. Chaque expiration vous permet d\'aller un peu plus loin.',
      voixFin: 'Excellent étirement ! La souplesse unilatérale est importante pour l\'équilibre musculaire. Continuez régulièrement !',
    ),
    Exercise(
      id: 'ex_standing_pelvis_tilt',
      name: 'Standing Posterior Pelvis Tilt',
      description: 'Rétroversion du bassin debout — rééducation posturale essentielle',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'bas_dos',
      type: 'posture',
      videoUrl: null,
      series: 2,
      reps: 15,
      dureeSerieSec: 0,
      reposSec: 20,
      typeComptage: 'reps',
      voixIntro: 'Rétroversion du bassin debout. Debout, dos droit, légèrement près d\'un mur si besoin. Mains sur les hanches pour sentir le mouvement.',
      voixPendant: 'Contractez les abdominaux et les fessiers ensemble pour basculer le bassin vers l\'avant et effacer la cambrure. Tenez 5 secondes. Relâchez. Recommencez.',
      voixFin: 'Ce petit exercice a un grand impact. Pratiquez-le quotidiennement et votre posture s\'améliorera nettement. Bravo !',
    ),
    Exercise(
      id: 'ex_touch_sky_forward_fold',
      name: 'Touch Sky Forward Fold',
      description: 'Enchaînement vers le ciel et flexion avant en vague',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'dos',
      type: 'etirement',
      videoUrl: null,
      series: 1,
      reps: 10,
      dureeSerieSec: 0,
      reposSec: 0,
      typeComptage: 'reps',
      voixIntro: 'Touch Sky Forward Fold. Debout, pieds écartés largeur de hanches. Un mouvement de vague qui réveille tout le corps.',
      voixPendant: 'Levez les bras vers le ciel, grandissez-vous — inspirez à fond. Puis penchez-vous vers l\'avant, mains vers le sol — expirez tout. Genoux légèrement fléchis. Remontez doucement.',
      voixFin: 'Ce mouvement de vague revitalise tout l\'organisme. Parfait pour commencer ou finir une journée. Magnifique !',
    ),
    Exercise(
      id: 'ex_trapezes_superieurs',
      name: 'Trapèzes supérieurs',
      description: 'Étirement des trapèzes supérieurs et de la nuque',
      duration: 3,
      difficulty: 'facile',
      targetZone: 'trapezes',
      type: 'mobilite',
      videoUrl: null,
      series: 2,
      reps: 0,
      dureeSerieSec: 25,
      reposSec: 10,
      typeComptage: 'chrono_par_cote',
      voixIntro: 'Étirement des trapèzes supérieurs. Assis ou debout, dos droit. Inclinez lentement la tête vers l\'épaule droite.',
      voixPendant: 'Laissez le bras gauche pendre ou posez-le dans le dos. Sentez l\'étirement le long du côté gauche du cou. Maintenez 25 secondes. Respirez doucement.',
      voixFin: 'Vos trapèzes sont soulagés. Après une journée devant un écran, c\'est exactement ce dont votre cou avait besoin. Prenez soin de vous !',
    ),
  ];

}
